uploads = []
outputs = []

[[generated]]
id = "p_rKBSmGAF1ZgErNwUYgI"
uri = "file://artifacts/cr-industries/public/steps/step1.png"
type = "image"
title = "gum hydra waterproof sealant concrete"

[[generated]]
id = "3dvLFF6lrW2ByAGcGNFGr"
uri = "file://artifacts/cr-industries/public/steps/step2.png"
type = "image"
title = "pipe thread sealant compound"

[[generated]]
id = "EpjWIkdZELrXZgVAor6WG"
uri = "file://artifacts/cr-industries/public/steps/step3.png"
type = "image"
title = "precision industrial chrome tap fitting"

[[generated]]
id = "t_F-pR9MkcYQPxbsDYNKv"
uri = "file://artifacts/cr-industries/public/steps/step4.png"
type = "image"
title = "industrial angle grinder sparks metal"

[[generated]]
id = "6LdT_w37iIivEdN2U2SiN"
uri = "file://artifacts/cr-industries/public/steps/step5.png"
type = "image"
title = "industrial gasket seal pipe flange"

[[generated]]
id = "4xklLahMdgVX65cExlrCJ"
uri = "file://artifacts/cr-industries/public/steps/step6.png"
type = "image"
title = "silicone sealant cartridge metal joint"
